config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  devise_for :users
  resources :categories do
    resources :deals
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    return unless user.present?

    can :manage, Category, author_id: user.id
    can :manage, Deal, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_deal.rb
class CategoriesDeal < ApplicationRecord
  belongs_to :category
  belongs_to :deal
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_and_belongs_to_many :deals, dependent: :destroy

  validates :name, :icon, presence: true
  has_one_attached :icon, dependent: :destroy
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_and_belongs_to_many :categories, dependent: :destroy

  validates :name, :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, foreign_key: 'author_id', dependent: :destroy
  has_many :deals, foreign_key: 'author_id', dependent: :destroy
  has_one_attached :photo, dependent: :destroy
  validates :photo, presence: true
  validates :name, presence: true, length: { maximum: 25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :allowed_params, if: :devise_controller?

  # Catch all CanCan errors and alert the user of the exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  # after successfull sign_up/sign_in devise method automatically will go
  def after_sign_in_path_for(_resource)
    categories_path
  end

  protected

  def allowed_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[photo name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password current_password photo])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
    @category_totals = {}

    @categories.each do |category|
      @category_totals[category.id] = category.deals.sum(:amount)
    end

    @total_payment = @category_totals.values.sum
  end

  def show
    @category = Category.find(params[:id])
    @total = @category.deals.sum(:amount)
    @deals = @category.deals.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.author_id = current_user.id
    if @category.save
      flash[:success] = 'Category succesfully added'
      redirect_to categories_path
    else
      flash[:error] = 'Error: Category could not be added'
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = 'Category removed successfully'
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def show
    @deal = Deal.find(params[:id])
    @category = @deal.categories.first # Assuming a deal has one category, adjust accordingly

    # Fetch all deals that belong to the same category as the current deal
    @user_deals = @category.deals.where(author_id: current_user.id)
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(name: deals_params[:name], amount: deals_params[:amount])

    @deal.author_id = current_user.id
    if @deal.save
      CategoriesDeal.create(deal: @deal, category_id: deals_params[:category_id])
      flash[:success] = 'Payment succesful'
      redirect_to edit_category_deal_path(category_id: deals_params[:category_id], id: @deal.id)

    else
      flash[:error] = 'Error: payment could not be added'
      render :new
    end
  end

  def edit; end

  private

  def deals_params
    params.require(:deal).permit(:name, :amount, :category_id, :author_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/index.html.erb
<div class="added_button">
  <section class="home-section category_list">
    <div>
      <nav>
        <%= link_to raw('<i class="fa-solid fa-arrow-left-long"></i>'), root_path %>
        <h1>PAYMENT TYPE</h1>
        <i class="fa-solid fa-magnifying-glass fa-shake fa-sm" style="color: #fff;"></i>
      </nav>
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <div class="user_total_payment category_details">
      <h3>Sum Of All Transaction: </h3>
      <h3> $<%= @total_payment%></h3>

      </div>
      <div id="categories">
        <% @categories.each do |category| %>
          <% if can? :manage, category %>
            <%= link_to category do %>
              <div class="category_details">
                <% if category.icon.attached? %>
                  <div class="display_flex">
                    <%= image_tag category.icon, class: "category_icon_manage" %>
                  <% else %>
                    <i class="fa-solid fa-2xl fa-circle-user" style="color: #7e7575;"></i>
                  <% end %>
                  <div class="name_date">
                    <%= category.name.capitalize %>
                    <p><%= category.created_at.strftime("%d %b %Y") %></p>
                  </div>
                </div>
                <p>Total Payment: $<%= @category_totals[category.id] %></p>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
  <% if current_user.categories.empty? %>
    <h2 class="no_payment">You haven't added any Payment Type yet!</h2>
  <% end %>
</div>
<section>
  <button class="editBtn margin_top">
    <%= link_to "Add Payment", new_category_path, class: "outline_border" %>
  <button>
</section>

app/views/categories/new.html.erb
<section class="home-section category_form">
   <nav>
     <i class="fa-solid fa-shake fa-bars menu_toggle" onclick="toggleMenu()"></i>
        <h1>PAYMENT TYPE</h1>
      <%= link_to raw('<i class="fa-solid fa-arrow-left-long"></i>'), categories_path %>
    </nav>
     <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
     </div>
     <%= render "layouts/shared/mobile_nav" %>

<%= form_with(model: @category, html: { class: "position_bottom" }) do |form| %>
  <% if @category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :author_id, value: current_user.id %>
   <div class="category_name_icon input-field-container">
   <div>
    <%= form.label :name, style:"display:none" %>
    <%= form.text_field :name,class:"category_name", placeholder:"Enter Category Name" %>
    <div class="upload-container">
       <i class="fa-solid fa-2xl fa-circle-user" style="color: #7e7575;"></i>
        <span class="upload-placeholder">Upload Icon</span>
       <%= form.file_field :icon, accept: "image/*", class:"user-photo" %>
     </div>
   </div>
   </div>
   <button  class="createCategoryBtn">
   <%= form.submit "Create Payment Type", class:"outline_border"%>
   </button>

  <% end %>
</section>

app/views/categories/show.html.erb
<section class="home-section category_details_page">
  <div>
    <nav>
      <%= link_to raw('<i class="fa-solid fa-arrow-left-long"></i>'), categories_path %>
      <h1>Transaction</h1>
      <i class="fa-solid fa-magnifying-glass fa-shake fa-sm" style="color: #fff;"></i>
    </nav>
    <%= link_to category_deal_path(@category) do %>
    <div class="category_details">
      <% if can? :manage, @category %>
        <% if @category.icon.attached? %>
          <div class="display_flex">
            <%= image_tag @category.icon, class: "category_icon_manage" %>
          <% else %>
            <i class="fa-solid fa-2xl fa-circle-user" style="color: #7e7575;"></i>
          <% end %>
          <div class="name_date">
            <%= @category.name.capitalize %>
            <p><%= @category.created_at.strftime("%d-%m-%y at %l:%M:%S %p") %></p>
            <h3>See Details</h3>
          </div>
        </div>
        <p>Total Payment: $<%= @total %></p>
      <% end %>
    </div>
    <%end%>
  </div>
  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  <div class="action_category_btn">
    <%= link_to "Make Payment", new_category_deal_path(@category), class: "outline_border" %>
    <%= button_to "Destroy this category", category_path(@category), method: :delete, class: "deleteBtn", data: { turbo_method: :delete, turbo_confirm: 'Are you sure to delete?' } %>
  </div>
</section>

app/views/deals/edit.html.erb
<section class="home-section successful_payment">
<nav>
      <%= link_to raw('<i class="fa-solid fa-arrow-left-long"></i>'), category_deal_path %>
      <h1>PAYMENT</h1>
      <i class="fa-solid fa-magnifying-glass fa-shake fa-sm" style="color: #fff;"></i>
 </nav>
   <div class="icon_completed">
     <i class="fa-solid fa-circle-check fa-beat fa-xl" style="color: #5fb523;"></i>
      <h3>Complete</h3>
      <p>Payment Was Completed Successfully!</p>
   </div>
 </section>

app/views/deals/new.html.erb
  <section class="home-section new_deal">
    <nav>
     <i class="fa-solid fa-shake fa-bars menu_toggle" onclick="toggleMenu()"></i>
        <h1>CREATE PAYMENT</h1>
      <%= link_to raw('<i class="fa-solid fa-arrow-left-long"></i>'), categories_path %>
    </nav
     <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
     </div>
     <%= render "layouts/shared/mobile_nav" %>
      <%= form_with model: @deal, url: category_deals_path(params[:category_id]), method: :post, local: true do |form| %>
      <%= form.hidden_field :category_id, value: params[:category_id] %>

  <% if @deal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>
      <ul>
        <% @deal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-field-container">
    <%= form.hidden_field :author_id, value: current_user.id %>
    <% form.label :category_id %>
    <%= form.collection_select :category_id, current_user.categories, :id, :name, prompt: "Select a category" %>
    <%= form.label :name, style: "display: none" %>
    <%= form.text_field :name, require: true, placeholder: "Enter Payment Name" %>
    <%= form.label :amount, style: "display: none" %>
    <%= form.text_field :amount, require: true, placeholder: "Amount" %>
  </div>
    <button  class="createCategoryBtn">
   <%= form.submit "Confirm Payment", class:"outline_border"%>
   </button>
<% end %>
</section>

app/views/deals/show.html.erb
<!-- app/views/deals/show.html.erb -->

<section class="home-section category_details_page">
  <div>
    <nav>
      <%= link_to raw('<i class="fa-solid fa-arrow-left-long"></i>'), categories_path %>
      <h1>Transaction Details</h1>
      <i class="fa-solid fa-magnifying-glass fa-shake fa-sm" style="color: #fff;"></i>
    </nav>
    <div class="category_details">
      <% if can? :manage, @category %>
        <% if @category.icon.attached? %>
          <div class="display_flex">
            <%= image_tag @category.icon, class: "category_icon_manage" %>
          <% else %>
            <i class="fa-solid fa-2xl fa-circle-user" style="color: #7e7575;"></i>
          <% end %>
          <div class="name_date">
            <%= @category.name.capitalize %>
            <p><%= @category.created_at.strftime("%d-%m-%y at %l:%M:%S %p") %></p>
          </div>
        </div>
      <p>Total Payment:</p>
      <p> $<%= @user_deals.sum(:amount) %></p>
      <% end %>
    </div>
  </div>
  <div class="Transaction_list">
  <table style="width: 100%; border-collapse: collapse;">
    <thead>
      <tr>
        <th style="border: 1px solid #000; padding: 8px;">Transaction Name</th>
        <th style="border: 1px solid #000; padding: 8px;">Payment Amount</th>
        <th style="border: 1px solid #000; padding: 8px;"> Time</th>
      </tr>
    </thead>
    <tbody>
      <% @user_deals.each do |deal| %>
        <tr>
          <td style="border: 1px solid #000; padding: 8px;"><%= deal.name %></td>
          <td style="border: 1px solid #000; padding: 8px;"><%= deal.amount %></td>
          <td style="border: 1px solid #000; padding: 8px;"><%= deal.created_at.strftime("%d-%m-%Y %H:%M:%S") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpendiGo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<body>
    <%= yield %>
</body>
</html>

app/views/layouts/shared/_mobile_nav.html.erb
<% if user_signed_in? %>
<div class="menu_container">
  <i class="fa-solid fa-xmark" style="color: #fff; display: none;" onclick="toggleMenu()"></i>
  <div class="profile_info">
    <div class="profile-img">
      <% if current_user.photo.present? %>
        <%= image_tag current_user.photo, class: "avatar_circle" %>
      <% else %>
        <i class="fa-solid fa-2xl fa-circle-user avatar_circle" style="color: #7e7575;"></i>
      <% end %>
    </div>
    <p><%= current_user.name %></p>
  </div>
  <ul class="menu_list">
  <li class="menu_item"><i class="fa-solid fa-gear fa-spin" style="color: #fff;"></i><a href="/users/edit"><span>Account Settings</span></a></li>
  <li class="menu_item"><i class="fa-solid fa-pen-nib" style="color: #ffffff;"></i><a href="#"><span>Merchant Finder</span></a></li>
  <li class="menu_item"><i class="fa-solid fa-pen-nib" style="color: #ffffff;"></i><a href="#"><span>Claim Promo</span></a></li>
  <li class="menu_item"><i class="fa-solid fa-pen-nib" style="color: #ffffff;"></i><a href="#"><span>Share Promo</span></a></li>
  <li class="menu_item"><i class="fa-solid fa-rotate fa-spin" style="color: #ffffff;"></i><a href="/categories"><span>Payments</span></a></li>
  <li class="menu_item">
    <i class="fa-solid fa-sign-out"></i><%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure to logout?' } %>
  </li>
</ul>

</div>
<% end %>

<script>
function toggleMenu() {
  const menuContainer = document.querySelector('.menu_container');
  const closeBtn = document.querySelector('.menu_container .fa-xmark');
  const openBtn = document.querySelector('.menu_container .fa-bars');

  menuContainer.classList.toggle('active');
  closeBtn.style.display = closeBtn.style.display === 'none' ? 'inline-block' : 'none';
  openBtn.style.display = openBtn.style.display === 'none' ? 'inline-block' : 'none';
}

function closeMenu() {
  const menuContainer = document.querySelector('.menu_container');
  const closeBtn = document.querySelector('.menu_container .fa-xmark');
  const openBtn = document.querySelector('.menu_container .fa-bars');

  if (menuContainer.classList.contains('active')) {
    menuContainer.classList.remove('active');
    closeBtn.style.display = 'none';
    openBtn.style.display = 'inline-block';
  }
}
</script>

app/views/splash/index.html.erb
<section class='home-section current_user'>
  <% if current_user  %>
     <nav>
    <p class="menu_test"> <i class="fa-solid fa-shake fa-bars menu_toggle" onclick="toggleMenu()"></i></p>
        <h1>HOME</h1>
        <i class="fa-solid fa-magnifying-glass fa-shake fa-sm" style="color: #fff;"></i>
      </nav>
     <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </div>
     <%= render "layouts/shared/mobile_nav" %>
  <h1 class="welcome">Welcome, <span><%= current_user.name %>!</span><h1>
<% else  %>
        <div class='splash-home'>
            <h1>Wecome To SpendiGo!<h1>
            <p>Track Your Spending Smartly</p>
            <%= image_tag('logo.png', width: '170px', height: '200px') %>
            <p>SpendiGo</p>
        </div>
         <div class="action-div">
           <%= link_to "LOG IN", new_user_session_path, class:"login"%>
           <%= link_to "SIGN UP", new_user_registration_path, class:"signup"%>
          </div>
     <% end %>
</section>